version: 2
jobs:
  build:
    docker:
      - image: classmethod/openjdk-with-git:8-jdk
    environment:
      _JAVA_OPTIONS: -Xmx3G
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - spring-data-mirage-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - spring-data-mirage-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}
            - spring-data-mirage-{{ .Branch }}
            - spring-data-mirage-develop
            - spring-data-mirage-master
      - run:
          name: Show version
          command: ./gradlew -v
      - run:
          name: Resolve dependencies
          command: ./gradlew resolveDependencies
      - run:
          name: Run tests
          command: ./gradlew check jacocoTestReport
      - run:
          name: Run build
          command: ./gradlew build
      - store_artifacts:
          name: Store artifacts
          path: build/reports
          destination: artifacts
      - store_test_results:
          path: build/test-results
      - deploy:
          name: Deploy artifacts
          command: |
            ./gradlew assemble publish showVersion
      - save_cache:
          key: spring-data-mirage-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle"
            - "~/.m2"
